// Auto-generated Deno Edge Function entry
// Source: supabase-functions/vibeusage-debug-auth.js
// @ts-nocheck

import { createClient as __supabase_createClient__ } from "https://esm.sh/@supabase/supabase-js@2";

const __corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, apikey",
};
let __bundleError: string | null = null;
let __handler: ((req: Request) => Response | Promise<Response>) | null = null;

try {
// Generated by scripts/build-supabase-functions.cjs. DO NOT EDIT.

var __getOwnPropNames = Object.getOwnPropertyNames;
// __require polyfill removed for Deno compatibility
var __commonJS = (cb, mod) => function __require2() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};

// supabase-src/shared/http.js
var require_http = __commonJS({
  "supabase-src/shared/http.js"(exports, module) {
    "use strict";
    var corsHeaders = {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, Authorization, apikey"
    };
    function handleOptions(request) {
      if (request.method === "OPTIONS") {
        return new Response(null, { status: 204, headers: corsHeaders });
      }
      return null;
    }
    function json(body, status = 200, extraHeaders = null) {
      return new Response(JSON.stringify(body), {
        status,
        headers: {
          ...corsHeaders,
          "Content-Type": "application/json",
          ...extraHeaders || {}
        }
      });
    }
    function requireMethod(request, method) {
      if (request.method !== method) return json({ error: "Method not allowed" }, 405);
      return null;
    }
    async function readJson(request) {
      if (!request.headers.get("Content-Type")?.includes("application/json")) {
        return { error: "Content-Type must be application/json", status: 415, data: null };
      }
      try {
        const data = await request.json();
        return { error: null, status: 200, data };
      } catch (_e) {
        return { error: "Invalid JSON", status: 400, data: null };
      }
    }
    module.exports = {
      corsHeaders,
      handleOptions,
      json,
      requireMethod,
      readJson
    };
  }
});

// supabase-src/shared/env.js
var require_env = __commonJS({
  "supabase-src/shared/env.js"(exports, module) {
    "use strict";
    function getBaseUrl() {
      return Deno.env.get("SUPABASE_URL") || Deno.env.get("SUPABASE_INTERNAL_URL") || "http://supabase:7130";
    }
    function getServiceRoleKey() {
      return Deno.env.get("SERVICE_ROLE_KEY") || Deno.env.get("API_KEY") || Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || null;
    }
    function getAnonKey() {
      return Deno.env.get("ANON_KEY") || Deno.env.get("SUPABASE_ANON_KEY") || null;
    }
    function getJwtSecret() {
      return Deno.env.get("SUPABASE_JWT_SECRET") || Deno.env.get("SUPABASE_JWT_SECRET") || null;
    }
    module.exports = {
      getBaseUrl,
      getServiceRoleKey,
      getAnonKey,
      getJwtSecret
    };
  }
});

// supabase-src/shared/public-view.js
var require_public_view = __commonJS({
  "supabase-src/shared/public-view.js"(exports, module) {
    "use strict";
    var { createClient } = { createClient: __supabase_createClient__ };
    var { getAnonKey, getServiceRoleKey } = require_env();
    var PUBLIC_USER_TOKEN_RE = /^pv1-([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$/;
    async function resolvePublicView({ baseUrl, shareToken }) {
      const token = normalizeShareToken(shareToken);
      if (!token) {
        return { ok: false, edgeClient: null, userId: null };
      }
      const serviceRoleKey = getServiceRoleKey();
      if (!serviceRoleKey) return { ok: false, edgeClient: null, userId: null };
      const anonKey = getAnonKey();
      const dbClient = createClient(baseUrl, anonKey || serviceRoleKey, {
        auth: { autoRefreshToken: false, persistSession: false, detectSessionInUrl: false },
        global: {
          headers: { Authorization: `Bearer ${serviceRoleKey}` }
        }
      });
      dbClient.database = dbClient;
      const resolvedUserId = await resolvePublicUserId({ dbClient, token });
      if (!resolvedUserId) {
        return { ok: false, edgeClient: null, userId: null };
      }
      const { data: settings, error: settingsErr } = await dbClient.from("vibeusage_user_settings").select("leaderboard_public").eq("user_id", resolvedUserId).maybeSingle();
      if (settingsErr || settings?.leaderboard_public !== true) {
        return { ok: false, edgeClient: null, userId: null };
      }
      return { ok: true, edgeClient: dbClient, userId: resolvedUserId };
    }
    async function resolvePublicUserId({ dbClient, token }) {
      if (!dbClient || !token) return null;
      const { data, error } = await dbClient.from("vibeusage_public_views").select("user_id").eq("user_id", token.userId).is("revoked_at", null).maybeSingle();
      if (error || !data?.user_id) return null;
      return data.user_id;
    }
    function normalizeToken(value) {
      if (typeof value !== "string") return null;
      const token = value.trim();
      if (!token) return null;
      if (token.length > 256) return null;
      return token;
    }
    function normalizeShareToken(value) {
      const token = normalizeToken(value);
      if (!token) return null;
      const normalized = token.toLowerCase();
      if (token !== normalized) return null;
      const publicUserMatch = normalized.match(PUBLIC_USER_TOKEN_RE);
      if (publicUserMatch?.[1]) {
        return { kind: "user", userId: publicUserMatch[1] };
      }
      return null;
    }
    function isPublicShareToken(value) {
      return Boolean(normalizeShareToken(value));
    }
    module.exports = {
      resolvePublicView,
      isPublicShareToken
    };
  }
});

// supabase-src/shared/auth.js
var require_auth = __commonJS({
  "supabase-src/shared/auth.js"(exports, module) {
    "use strict";
    var { createClient } = { createClient: __supabase_createClient__ };
    var { getAnonKey, getJwtSecret } = require_env();
    var { resolvePublicView, isPublicShareToken } = require_public_view();
    function getBearerToken(headerValue) {
      if (!headerValue) return null;
      const prefix = "Bearer ";
      if (!headerValue.startsWith(prefix)) return null;
      const token = headerValue.slice(prefix.length).trim();
      return token.length > 0 ? token : null;
    }
    function decodeBase64Url(value) {
      if (typeof value !== "string") return null;
      let s = value.replace(/-/g, "+").replace(/_/g, "/");
      const pad = s.length % 4;
      if (pad) s += "=".repeat(4 - pad);
      try {
        if (typeof atob === "function") return atob(s);
      } catch (_e) {
      }
      try {
        if (typeof Buffer !== "undefined") {
          return Buffer.from(s, "base64").toString("utf8");
        }
      } catch (_e) {
      }
      return null;
    }
    function decodeJwtPayload(token) {
      if (typeof token !== "string") return null;
      const parts = token.split(".");
      if (parts.length < 2) return null;
      const raw = decodeBase64Url(parts[1]);
      if (!raw) return null;
      try {
        return JSON.parse(raw);
      } catch (_e) {
        return null;
      }
    }
    function decodeJwtHeader(token) {
      if (typeof token !== "string") return null;
      const parts = token.split(".");
      if (parts.length < 2) return null;
      const raw = decodeBase64Url(parts[0]);
      if (!raw) return null;
      try {
        return JSON.parse(raw);
      } catch (_e) {
        return null;
      }
    }
    function getJwtRole(token) {
      const payload = decodeJwtPayload(token);
      const role = payload?.role;
      if (typeof role === "string" && role.length > 0) return role;
      const appRole = payload?.app_metadata?.role;
      if (typeof appRole === "string" && appRole.length > 0) return appRole;
      const roles = payload?.app_metadata?.roles;
      if (Array.isArray(roles)) {
        if (roles.includes("project_admin")) return "project_admin";
        const match = roles.find((value) => typeof value === "string" && value.length > 0);
        if (match) return match;
      }
      return null;
    }
    function isProjectAdminBearer(token) {
      const role = getJwtRole(token);
      return role === "project_admin";
    }
    function isJwtExpired(payload) {
      const exp = Number(payload?.exp);
      if (!Number.isFinite(exp)) return false;
      return exp * 1e3 <= Date.now();
    }
    function base64UrlEncode(value) {
      let base64 = null;
      try {
        if (typeof Buffer !== "undefined") {
          base64 = Buffer.from(value).toString("base64");
        }
      } catch (_e) {
      }
      if (!base64 && typeof btoa === "function" && value instanceof ArrayBuffer) {
        const bytes = new Uint8Array(value);
        let binary = "";
        for (const byte of bytes) binary += String.fromCharCode(byte);
        base64 = btoa(binary);
      }
      if (!base64) return null;
      return base64.replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_");
    }
    async function verifyUserJwtHs256({ token }) {
      const secret = getJwtSecret();
      if (!secret) {
        return { ok: false, userId: null, error: "Missing jwt secret", code: "missing_jwt_secret" };
      }
      if (typeof token !== "string") {
        return { ok: false, userId: null, error: "Invalid token" };
      }
      const parts = token.split(".");
      if (parts.length !== 3) {
        return { ok: false, userId: null, error: "Invalid token" };
      }
      const header = decodeJwtHeader(token);
      if (!header || header.alg !== "HS256") {
        return { ok: false, userId: null, error: "Unsupported alg" };
      }
      const payload = decodeJwtPayload(token);
      if (!payload) {
        return { ok: false, userId: null, error: "Invalid payload" };
      }
      const exp = Number(payload?.exp);
      if (!Number.isFinite(exp)) {
        return { ok: false, userId: null, error: "Missing exp" };
      }
      if (isJwtExpired(payload)) {
        return { ok: false, userId: null, error: "Token expired" };
      }
      const cryptoSubtle = globalThis.crypto?.subtle;
      if (!cryptoSubtle) {
        return { ok: false, userId: null, error: "Crypto unavailable" };
      }
      const data = `${parts[0]}.${parts[1]}`;
      const encoder = new TextEncoder();
      const key = await cryptoSubtle.importKey(
        "raw",
        encoder.encode(secret),
        { name: "HMAC", hash: "SHA-256" },
        false,
        ["sign"]
      );
      const signature = await cryptoSubtle.sign("HMAC", key, encoder.encode(data));
      const expected = base64UrlEncode(signature);
      if (!expected || expected !== parts[2]) {
        return { ok: false, userId: null, error: "Invalid signature" };
      }
      const userId = typeof payload.sub === "string" ? payload.sub : null;
      if (!userId) {
        return { ok: false, userId: null, error: "Missing sub" };
      }
      return { ok: true, userId, error: null };
    }
    async function getEdgeClientAndUserId({ baseUrl, bearer }) {
      const auth = await getEdgeClientAndUserIdFast({ baseUrl, bearer });
      if (!auth.ok) {
        return {
          ok: false,
          edgeClient: null,
          userId: null,
          status: auth.status ?? 401,
          error: auth.error ?? "Unauthorized",
          code: auth.code ?? null
        };
      }
      return { ok: true, edgeClient: auth.edgeClient, userId: auth.userId };
    }
    async function getEdgeClientAndUserIdFast({ baseUrl, bearer }) {
      const anonKey = getAnonKey();
      const edgeClient = createClient(baseUrl, anonKey || "", {
        auth: { autoRefreshToken: false, persistSession: false, detectSessionInUrl: false },
        global: {
          headers: bearer ? { Authorization: `Bearer ${bearer}` } : {}
        }
      });
      edgeClient.database = edgeClient;
      const local = await verifyUserJwtHs256({ token: bearer });
      const allowRemoteOnly = !local.ok && local?.code === "missing_jwt_secret";
      if (!local.ok && !allowRemoteOnly) {
        return {
          ok: false,
          edgeClient: null,
          userId: null,
          status: 401,
          error: "Unauthorized",
          code: local?.code || "invalid_jwt"
        };
      }
      if (typeof edgeClient?.auth?.getUser !== "function") {
        return {
          ok: false,
          edgeClient: null,
          userId: null,
          status: 503,
          error: "Service unavailable",
          code: "missing_auth_client"
        };
      }
      let authResult = null;
      try {
        authResult = await edgeClient.auth.getUser(bearer);
      } catch (e) {
        const message = getAuthFailureMessage(e);
        const status = classifyAuthFailure({
          status: normalizeHttpStatus(e?.statusCode ?? e?.status),
          message
        });
        return {
          ok: false,
          edgeClient: null,
          userId: null,
          status,
          error: status === 503 ? "Service unavailable" : "Unauthorized",
          code: "auth_lookup_failed"
        };
      }
      const authUserId = authResult?.data?.user?.id || null;
      if (!authUserId || authResult?.error) {
        const message = getAuthFailureMessage(authResult?.error) || (!authUserId ? "User missing" : "");
        const status = classifyAuthFailure({
          status: normalizeHttpStatus(authResult?.error?.statusCode ?? authResult?.error?.status),
          message
        });
        return {
          ok: false,
          edgeClient: null,
          userId: null,
          status,
          error: status === 503 ? "Service unavailable" : "Unauthorized",
          code: "auth_lookup_failed"
        };
      }
      if (!allowRemoteOnly && authUserId !== local.userId) {
        return {
          ok: false,
          edgeClient: null,
          userId: null,
          status: 401,
          error: "Unauthorized",
          code: "user_mismatch"
        };
      }
      return { ok: true, edgeClient, userId: authUserId };
    }
    async function getAccessContext({ baseUrl, bearer, allowPublic = false }) {
      if (!bearer) {
        return {
          ok: false,
          edgeClient: null,
          userId: null,
          accessType: null,
          status: 401,
          error: "Unauthorized",
          code: "missing_bearer"
        };
      }
      const auth = await getEdgeClientAndUserIdFast({ baseUrl, bearer });
      if (auth.ok) {
        return { ok: true, edgeClient: auth.edgeClient, userId: auth.userId, accessType: "user" };
      }
      if (!allowPublic) {
        return {
          ok: false,
          edgeClient: null,
          userId: null,
          accessType: null,
          status: auth.status ?? 401,
          error: auth.error ?? "Unauthorized",
          code: auth.code ?? null
        };
      }
      if (!isPublicShareToken(bearer)) {
        return {
          ok: false,
          edgeClient: null,
          userId: null,
          accessType: null,
          status: auth.status ?? 401,
          error: auth.error ?? "Unauthorized",
          code: auth.code ?? null
        };
      }
      const publicView = await resolvePublicView({ baseUrl, shareToken: bearer });
      if (!publicView.ok) {
        return {
          ok: false,
          edgeClient: null,
          userId: null,
          accessType: null,
          status: 401,
          error: "Unauthorized"
        };
      }
      return {
        ok: true,
        edgeClient: publicView.edgeClient,
        userId: publicView.userId,
        accessType: "public"
      };
    }
    module.exports = {
      getBearerToken,
      getAccessContext,
      getEdgeClientAndUserId,
      getEdgeClientAndUserIdFast,
      isProjectAdminBearer,
      verifyUserJwtHs256
    };
    function normalizeHttpStatus(value) {
      const n = Number(value);
      if (!Number.isFinite(n)) return null;
      const status = Math.trunc(n);
      if (status < 100 || status > 599) return null;
      return status;
    }
    function getAuthFailureMessage(err) {
      if (!err) return "";
      if (typeof err === "string") return err;
      if (typeof err?.message === "string") return err.message;
      if (typeof err?.error === "string") return err.error;
      return "";
    }
    function classifyAuthFailure({ status, message } = {}) {
      const normalizedStatus = normalizeHttpStatus(status);
      if (normalizedStatus === 401 || normalizedStatus === 403) return 401;
      if (normalizedStatus != null) return 503;
      if (isRetryableAuthMessage(message)) return 503;
      return 401;
    }
    function isRetryableAuthMessage(message) {
      const s = String(message || "").toLowerCase();
      if (!s) return false;
      if (s.includes("socket hang up")) return true;
      if (s.includes("econnreset") || s.includes("econnrefused")) return true;
      if (s.includes("etimedout") || s.includes("timeout") && s.includes("request")) return true;
      if (s.includes("networkerror") || s.includes("failed to fetch")) return true;
      if (s.includes("upstream") || s.includes("proxy")) return true;
      if (s.includes("deno")) return true;
      return false;
    }
  }
});

// supabase-src/functions/vibeusage-debug-auth.js
var require_vibeusage_debug_auth = __commonJS({
  "supabase-src/functions/vibeusage-debug-auth.js"(exports, module) {
    var { handleOptions, json, requireMethod } = require_http();
    var { getBearerToken, verifyUserJwtHs256 } = require_auth();
    var { getAnonKey } = require_env();
    module.exports = async function(request) {
      const opt = handleOptions(request);
      if (opt) return opt;
      const methodErr = requireMethod(request, "GET");
      if (methodErr) return methodErr;
      const anonKey = getAnonKey();
      const bearer = getBearerToken(request.headers.get("Authorization"));
      if (!anonKey) {
        return json(
          {
            hasAnonKey: false,
            hasBearer: Boolean(bearer),
            authOk: false,
            userId: null,
            error: "Missing anon key"
          },
          200
        );
      }
      if (!bearer) {
        return json(
          {
            hasAnonKey: true,
            hasBearer: false,
            authOk: false,
            userId: null,
            error: "Missing bearer token"
          },
          200
        );
      }
      const local = await verifyUserJwtHs256({ token: bearer });
      const authOk = local.ok;
      const userId = local.userId;
      const error = local.ok ? null : local.error || "Unauthorized";
      return json(
        {
          hasAnonKey: true,
          hasBearer: true,
          authOk,
          userId,
          error
        },
        200
      );
    };
  }
});

__handler = require_vibeusage_debug_auth();
} catch (e: any) {
  __bundleError = String(e?.stack || e);
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: __corsHeaders });
  }
  if (__bundleError) {
    return new Response(JSON.stringify({ error: "Bundle init failed", details: __bundleError }), {
      status: 500, headers: { ...__corsHeaders, "Content-Type": "application/json" },
    });
  }
  if (!__handler || typeof __handler !== "function") {
    return new Response(JSON.stringify({ error: "Handler not found", type: typeof __handler }), {
      status: 500, headers: { ...__corsHeaders, "Content-Type": "application/json" },
    });
  }
  try {
    return await __handler(req);
  } catch (e: any) {
    return new Response(JSON.stringify({ error: "Handler error", details: String(e?.stack || e) }), {
      status: 500, headers: { ...__corsHeaders, "Content-Type": "application/json" },
    });
  }
});
