// Auto-generated Deno Edge Function entry
// Source: supabase-functions/vibeusage-link-code-exchange.js
// @ts-nocheck


const __corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, apikey",
};
let __bundleError: string | null = null;
let __handler: ((req: Request) => Response | Promise<Response>) | null = null;

try {
// Generated by scripts/build-supabase-functions.cjs. DO NOT EDIT.

var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};

// supabase-src/shared/http.js
var require_http = __commonJS({
  "supabase-src/shared/http.js"(exports, module) {
    "use strict";
    var corsHeaders = {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, Authorization, apikey"
    };
    function handleOptions(request) {
      if (request.method === "OPTIONS") {
        return new Response(null, { status: 204, headers: corsHeaders });
      }
      return null;
    }
    function json(body, status = 200, extraHeaders = null) {
      return new Response(JSON.stringify(body), {
        status,
        headers: {
          ...corsHeaders,
          "Content-Type": "application/json",
          ...extraHeaders || {}
        }
      });
    }
    function requireMethod(request, method) {
      if (request.method !== method) return json({ error: "Method not allowed" }, 405);
      return null;
    }
    async function readJson(request) {
      if (!request.headers.get("Content-Type")?.includes("application/json")) {
        return { error: "Content-Type must be application/json", status: 415, data: null };
      }
      try {
        const data = await request.json();
        return { error: null, status: 200, data };
      } catch (_e) {
        return { error: "Invalid JSON", status: 400, data: null };
      }
    }
    module.exports = {
      corsHeaders,
      handleOptions,
      json,
      requireMethod,
      readJson
    };
  }
});

// supabase-src/shared/env.js
var require_env = __commonJS({
  "supabase-src/shared/env.js"(exports, module) {
    "use strict";
    function getBaseUrl() {
      return Deno.env.get("SUPABASE_URL") || Deno.env.get("SUPABASE_INTERNAL_URL") || "http://supabase:7130";
    }
    function getServiceRoleKey() {
      return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || Deno.env.get("SERVICE_ROLE_KEY") || Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || Deno.env.get("API_KEY") || null;
    }
    function getAnonKey() {
      return Deno.env.get("SUPABASE_ANON_KEY") || Deno.env.get("ANON_KEY") || Deno.env.get("SUPABASE_ANON_KEY") || null;
    }
    function getJwtSecret() {
      return Deno.env.get("SUPABASE_JWT_SECRET") || Deno.env.get("SUPABASE_JWT_SECRET") || null;
    }
    module.exports = {
      getBaseUrl,
      getServiceRoleKey,
      getAnonKey,
      getJwtSecret
    };
  }
});

// supabase-src/shared/crypto.js
var require_crypto = __commonJS({
  "supabase-src/shared/crypto.js"(exports, module) {
    "use strict";
    async function sha256Hex(input) {
      const data = new TextEncoder().encode(input);
      const hash = await crypto.subtle.digest("SHA-256", data);
      return Array.from(new Uint8Array(hash)).map((b) => b.toString(16).padStart(2, "0")).join("");
    }
    module.exports = {
      sha256Hex
    };
  }
});

// supabase-src/shared/logging.js
var require_logging = __commonJS({
  "supabase-src/shared/logging.js"(exports, module) {
    "use strict";
    function createRequestId() {
      if (globalThis?.crypto?.randomUUID) return globalThis.crypto.randomUUID();
      return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
    }
    function errorCodeFromStatus(status) {
      if (typeof status !== "number") return "UNKNOWN_ERROR";
      if (status >= 500) return "SERVER_ERROR";
      if (status >= 400) return "CLIENT_ERROR";
      return null;
    }
    function createLogger({ functionName }) {
      const requestId = createRequestId();
      const startMs = Date.now();
      let upstreamStatus = null;
      let upstreamLatencyMs = null;
      function recordUpstream(status, latencyMs) {
        upstreamStatus = typeof status === "number" ? status : null;
        upstreamLatencyMs = typeof latencyMs === "number" ? latencyMs : null;
      }
      async function fetchWithUpstream(url, init) {
        const upstreamStart = Date.now();
        try {
          const res = await fetch(url, init);
          recordUpstream(res.status, Date.now() - upstreamStart);
          return res;
        } catch (err) {
          recordUpstream(null, Date.now() - upstreamStart);
          throw err;
        }
      }
      function log({ stage, status, errorCode, ...extra }) {
        const payload = {
          ...extra || {},
          request_id: requestId,
          function: functionName,
          stage: stage || "response",
          status: typeof status === "number" ? status : null,
          latency_ms: Date.now() - startMs,
          error_code: errorCode ?? errorCodeFromStatus(status),
          upstream_status: upstreamStatus ?? null,
          upstream_latency_ms: upstreamLatencyMs ?? null
        };
        console.log(JSON.stringify(payload));
      }
      return {
        requestId,
        log,
        fetch: fetchWithUpstream
      };
    }
    function getResponseStatus(response) {
      if (response && typeof response.status === "number") return response.status;
      return null;
    }
    function resolveFunctionName(functionName, request) {
      if (request && typeof request.url === "string") {
        try {
          const url = new URL(request.url);
          const match = url.pathname.match(/\/functions\/([^/?#]+)/);
          if (match && match[1]) return match[1];
        } catch (_e) {
        }
      }
      return functionName;
    }
    function withRequestLogging(functionName, handler) {
      return async function(request) {
        const resolvedName = resolveFunctionName(functionName, request);
        const logger = createLogger({ functionName: resolvedName });
        try {
          const response = await handler(request, logger);
          const status = getResponseStatus(response);
          logger.log({ stage: "response", status });
          return response;
        } catch (err) {
          logger.log({ stage: "exception", status: 500, errorCode: "UNHANDLED_EXCEPTION" });
          throw err;
        }
      };
    }
    module.exports = {
      withRequestLogging,
      logSlowQuery,
      getSlowQueryThresholdMs
    };
    function logSlowQuery(logger, fields) {
      if (!logger || typeof logger.log !== "function") return;
      const durationMs = Number(fields?.duration_ms ?? fields?.durationMs);
      if (!Number.isFinite(durationMs)) return;
      const thresholdMs = getSlowQueryThresholdMs();
      if (durationMs < thresholdMs) return;
      logger.log({
        stage: "slow_query",
        status: 200,
        ...fields || {},
        duration_ms: Math.round(durationMs)
      });
    }
    function getSlowQueryThresholdMs() {
      const raw = readEnvValue("VIBEUSAGE_SLOW_QUERY_MS");
      if (raw == null || raw === "") return 2e3;
      const n = Number(raw);
      if (!Number.isFinite(n)) return 2e3;
      if (n <= 0) return 0;
      return clampInt(n, 1, 6e4);
    }
    function readEnvValue(key) {
      try {
        if (typeof Deno !== "undefined" && Deno?.env?.get) {
          const value = Deno.env.get(key);
          if (value !== void 0) return value;
        }
      } catch (_e) {
      }
      try {
        if (typeof process !== "undefined" && process?.env) {
          return process.env[key];
        }
      } catch (_e) {
      }
      return null;
    }
    function clampInt(value, min, max) {
      const n = Number(value);
      if (!Number.isFinite(n)) return min;
      return Math.min(max, Math.max(min, Math.floor(n)));
    }
  }
});

// supabase-src/functions/vibeusage-link-code-exchange.js
var require_vibeusage_link_code_exchange = __commonJS({
  "supabase-src/functions/vibeusage-link-code-exchange.js"(exports, module) {
    var { handleOptions, json, requireMethod, readJson } = require_http();
    var { getAnonKey, getBaseUrl, getServiceRoleKey } = require_env();
    var { sha256Hex } = require_crypto();
    var { withRequestLogging } = require_logging();
    var ISSUE_ERROR_MESSAGE = "Link code exchange failed";
    var DEVICE_NAME_FALLBACK = "VibeScore CLI";
    var PLATFORM_FALLBACK = "macos";
    module.exports = withRequestLogging("vibeusage-link-code-exchange", async function(request) {
      const opt = handleOptions(request);
      if (opt) return opt;
      const methodErr = requireMethod(request, "POST");
      if (methodErr) return methodErr;
      const body = await readJson(request);
      if (body.error) return json({ error: body.error }, body.status);
      const linkCode = sanitizeText(body.data?.link_code, 256);
      const requestId = sanitizeText(body.data?.request_id, 128);
      const deviceName = sanitizeText(body.data?.device_name, 128);
      const platform = sanitizeText(body.data?.platform, 32);
      if (!linkCode) return json({ error: "link_code is required" }, 400);
      if (!requestId) return json({ error: "request_id is required" }, 400);
      const baseUrl = getBaseUrl();
      const serviceRoleKey = getServiceRoleKey();
      if (!serviceRoleKey) return json({ error: "Missing service role key" }, 500);
      const anonKey = getAnonKey();
      const dbClient = createClient(baseUrl, anonKey || serviceRoleKey, {
        auth: { autoRefreshToken: false, persistSession: false, detectSessionInUrl: false },
        global: { headers: { Authorization: `Bearer ${serviceRoleKey}` } }
      });
      const codeHash = await sha256Hex(linkCode);
      const token = await deriveToken({ secret: serviceRoleKey, codeHash, requestId });
      const tokenHash = await sha256Hex(token);
      const { row: linkRow, error: linkErr } = await fetchLinkCodeRow({ dbClient, codeHash });
      if (linkErr) {
        logIssueError("link code select failed", linkErr?.message || ISSUE_ERROR_MESSAGE);
        return json({ error: ISSUE_ERROR_MESSAGE }, 500);
      }
      if (!linkRow) return json({ error: "invalid link code" }, 400);
      if (linkRow.used_at) {
        if (linkRow.request_id === requestId && typeof linkRow.device_id === "string") {
          return json({ token, device_id: linkRow.device_id, user_id: linkRow.user_id }, 200);
        }
        return json({ error: "link code already used" }, 409);
      }
      if (isExpired(linkRow.expires_at)) {
        return json({ error: "link code expired" }, 400);
      }
      const userId = linkRow.user_id;
      if (typeof userId !== "string" || userId.length === 0) {
        logIssueError("link code missing user_id", ISSUE_ERROR_MESSAGE);
        return json({ error: ISSUE_ERROR_MESSAGE }, 500);
      }
      const deviceId = crypto.randomUUID();
      const tokenId = crypto.randomUUID();
      const nowIso = (/* @__PURE__ */ new Date()).toISOString();
      const { error: deviceErr } = await dbClient.from("vibeusage_tracker_devices").insert([
        {
          id: deviceId,
          user_id: userId,
          device_name: deviceName || DEVICE_NAME_FALLBACK,
          platform: platform || PLATFORM_FALLBACK
        }
      ]);
      if (deviceErr) {
        logIssueError("device insert failed", deviceErr?.message || ISSUE_ERROR_MESSAGE);
        return json({ error: ISSUE_ERROR_MESSAGE }, 500);
      }
      const { error: tokenErr } = await dbClient.database.from("vibeusage_tracker_device_tokens").insert([
        {
          id: tokenId,
          user_id: userId,
          device_id: deviceId,
          token_hash: tokenHash
        }
      ]);
      if (tokenErr) {
        logIssueError("token insert failed", tokenErr?.message || ISSUE_ERROR_MESSAGE);
        await bestEffortDeleteDevice({ dbClient, deviceId, userId });
        return json({ error: ISSUE_ERROR_MESSAGE }, 500);
      }
      const { data: updatedRow, error: updateErr } = await dbClient.database.from("vibeusage_link_codes").update({ used_at: nowIso, request_id: requestId, device_id: deviceId }).eq("id", linkRow.id).is("used_at", null).select("user_id, device_id, request_id").maybeSingle();
      if (updateErr) {
        logIssueError("link code update failed", updateErr?.message || ISSUE_ERROR_MESSAGE);
        await bestEffortDeleteToken({ dbClient, tokenId });
        await bestEffortDeleteDevice({ dbClient, deviceId, userId });
        return json({ error: ISSUE_ERROR_MESSAGE }, 500);
      }
      if (updatedRow && typeof updatedRow.device_id === "string") {
        return json({ token, device_id: updatedRow.device_id, user_id: updatedRow.user_id }, 200);
      }
      await bestEffortDeleteToken({ dbClient, tokenId });
      await bestEffortDeleteDevice({ dbClient, deviceId, userId });
      const { row: freshRow } = await fetchLinkCodeRow({ dbClient, codeHash });
      if (freshRow && freshRow.request_id === requestId && typeof freshRow.device_id === "string") {
        return json({ token, device_id: freshRow.device_id, user_id: freshRow.user_id }, 200);
      }
      return json({ error: "link code already used" }, 409);
    });
    function sanitizeText(value, maxLen) {
      if (typeof value !== "string") return null;
      const s = value.trim();
      if (s.length === 0) return null;
      return s.length > maxLen ? s.slice(0, maxLen) : s;
    }
    async function deriveToken({ secret, codeHash, requestId }) {
      const input = `${secret}:${codeHash}:${requestId}`;
      return sha256Hex(input);
    }
    async function fetchLinkCodeRow({ dbClient, codeHash }) {
      const { data, error } = await dbClient.database.from("vibeusage_link_codes").select("id,user_id,expires_at,used_at,request_id,device_id").eq("code_hash", codeHash).maybeSingle();
      return { row: data || null, error };
    }
    function isExpired(expiresAt) {
      if (typeof expiresAt !== "string") return true;
      const ts = Date.parse(expiresAt);
      if (!Number.isFinite(ts)) return true;
      return ts <= Date.now();
    }
    async function bestEffortDeleteToken({ dbClient, tokenId }) {
      try {
        const { error } = await dbClient.database.from("vibeusage_tracker_device_tokens").delete().eq("id", tokenId);
        if (error) {
          logIssueError("compensation token delete failed", ISSUE_ERROR_MESSAGE);
        }
      } catch (_err) {
        logIssueError("compensation token delete threw", ISSUE_ERROR_MESSAGE);
      }
    }
    async function bestEffortDeleteDevice({ dbClient, deviceId, userId }) {
      try {
        let query = dbClient.from("vibeusage_tracker_devices").delete().eq("id", deviceId);
        if (userId) query = query.eq("user_id", userId);
        const { error } = await query;
        if (error) {
          logIssueError("compensation device delete failed", ISSUE_ERROR_MESSAGE);
        }
      } catch (_err) {
        logIssueError("compensation device delete threw", ISSUE_ERROR_MESSAGE);
      }
    }
    function logIssueError(stage, message) {
      console.error(`link code exchange ${stage}: ${message}`);
    }
  }
});

__handler = require_vibeusage_link_code_exchange();
} catch (e: any) {
  __bundleError = String(e?.stack || e);
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: __corsHeaders });
  }
  if (__bundleError) {
    return new Response(JSON.stringify({ error: "Bundle init failed", details: __bundleError }), {
      status: 500, headers: { ...__corsHeaders, "Content-Type": "application/json" },
    });
  }
  if (!__handler || typeof __handler !== "function") {
    return new Response(JSON.stringify({ error: "Handler not found", type: typeof __handler }), {
      status: 500, headers: { ...__corsHeaders, "Content-Type": "application/json" },
    });
  }
  try {
    return await __handler(req);
  } catch (e: any) {
    return new Response(JSON.stringify({ error: "Handler error", details: String(e?.stack || e) }), {
      status: 500, headers: { ...__corsHeaders, "Content-Type": "application/json" },
    });
  }
});
